# Generated by Django 3.2.9 on 2023-04-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
