# Generated by Django 3.2.9 on 2023-04-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0002_auto_20230416_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='email',
        ),
    ]
